server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true